sudo: false

before_install: umask 0022

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

scala:
  - 2.11.8

script:
  - sbt ++$TRAVIS_SCALA_VERSION compile test

jdk:
  - openjdk8
